[build]
target = "thumbv7m-none-eabi"

[target.thumbv7m-none-eabi]
runner = "probe-rs run --no-location --chip STM32F103C8Tx"

[profile.dev]
opt-level = "s"
lto = true

[profile.release]
debug = 2
# strip = true
opt-level = "s"
lto = true
DEFMT_LOG = "error"

[env]
DEFMT_LOG = "info"
